swagger: '2.0'
info:
  version: '1.0.0'
  title: test-store API
  description: API for test-store
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
basePath: /api
schemes:
  - http
consumes:
  - application/json
  - application/xml
produces:
  - application/json
paths:
  /testsuites:
    post:
      description: Creates a test suite
      consumes: 
        - application/json
      parameters:
        - name: testsuite
          in: body
          required: true
          schema:
            $ref: "#/definitions/testsuite"
      responses:
        '200':
          description: Testsuite has been created successfully
          schema:
            $ref: "#/definitions/testsuite-result"

  /testsuites/{testsuite_id}/runs:
    post:
      description: Creates a run
      consumes:
        - application/json
      parameters:
        - name: testsuite_id
          in: path
          description: ID of the testsuite for which the run shall be created
          required: true
          type: string
        - name: run
          description: The run to be created
          in: body
          required: true
          schema:
            $ref: "#/definitions/run"
      responses: 
        '201':
          description: Run has been created successfully
          schema:
            $ref: "#/definitions/run-result"

  /runs/{run_id}/results:
    post:
      consumes:
        - application/json
      description: Adds a result to the run
      parameters:
        - name: run_id
          in: path
          description: The UUID of the run for which the test result shall be inserted
          required: true
          type: string
        - name: result
          description: The result to be created
          in: body
          schema:
            $ref: "#/definitions/result"
      responses:
        '200':
          description: Asynchronous creation of run has been triggered succesfully

  /runs/{run_id}/results#xml:
    post: 
      consumes:
        - application/xml
      description: Adds a result in JUnit XML to the run
      parameters:
        - name: run_id
          in: path
          description: The UUID of the run  for which the test result shall be inserted
          required: true
          type: string
        - name: junit-xml
          in: body
          required: true
          description: The test result in JUnit XML
          schema:
            type: string
      responses:
        '200':
          description: Asynchronous insertion of the result has been triggered successfully

definitions:
  run:
    type: object
    required:
      - revision
      - time
    properties:
      revision:
        type: string
      time:
        type: string
  run-result:
    type: object
    required:
      - id
      - testSuite
      - revision
      - time
    properties:
      id:
        type: string
      testSuite:
        type: string
      revision:
        type: string
      time:
        type: string
  result:
    type: object
    required:
      - testName
      - retryNum
      - passed
      - durationMillis
      - time
    properties:
      testName:
        type: string
      retryNum:
        type: number
      passed:
        type: boolean
      durationMillis:
        type: number
      time:
        type: string
      stacktrace:
        type: string
  testsuite:
    type: object
    required:
      - name
    properties:
      name:
        type: string
  testsuite-result:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
